apiVersion: v1
kind: ReplicationController
metadata:
  name: test
  namespace: public
spec:
  replicas: 1
  selector:
    site: test
  template:
    metadata:
      labels:
        site: test
    spec:
      containers:
      - image: quay.io/kelseyhightower/hello
        name: test
